### ISSUE TITLE
is it possible to add a parameter to the function?

### ISSUE THREAD

**Issue by robobyt** [microsoft/pxt-brainpad#122]
I can easily add a parameter to the function in micro bit makecode, but not in brainpad,
![microbit](https://user-images.githubusercontent.com/46246572/61201711-09e5e780-a6ee-11e9-9ace-ae2a735c49a2.png)
![bp](https://user-images.githubusercontent.com/46246572/61201727-179b6d00-a6ee-11e9-9586-60c18934cd07.png)

**Comment by greg-norris** [comment]
Current version supports function parameters
